replicaCount: 1

dumper:
  logVerbosity: "http_dumper=info,tower_http=info"
  tls:
    # Path to a secret containing the keys. Leave empty if not using TLS.
    # dumper.crt   -- The certificate
    # dumper.key   -- The private key for the SSL Cert
    secret: ""

image:
  repository: quay.io/duk4s/httpdumper
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
